"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import {
  ArrowRight,
  Sparkles,
  Zap,
  BarChart3,
  Code,
  FileText,
  Shield,
  CheckCircle2,
  Star,
  Users,
  Laptop,
  Globe,
} from "lucide-react"
import { motion, useScroll, useTransform } from "framer-motion"
import { NewsletterForm } from "@/components/newsletter/newsletter-form"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { Menu, X } from "lucide-react"

export default function Home() {
  const [mounted, setMounted] = useState(false)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const { scrollYProgress } = useScroll()
  const opacity = useTransform(scrollYProgress, [0, 0.2], [1, 0])
  const y = useTransform(scrollYProgress, [0, 0.2], [0, -50])

  useEffect(() => {
    setMounted(true)
  }, [])

  const fadeIn = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 },
  }

  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  }

  const featureVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
  }

  const scaleUp = {
    hidden: { scale: 0.8, opacity: 0 },
    visible: { scale: 1, opacity: 1, transition: { duration: 0.5 } },
  }

  const slideIn = {
    hidden: { x: -60, opacity: 0 },
    visible: { x: 0, opacity: 1, transition: { duration: 0.5 } },
  }

  const stats = [
    { value: "10M+", label: "Words Generated" },
    { value: "5K+", label: "Active Users" },
    { value: "98%", label: "Satisfaction Rate" },
    { value: "24/7", label: "Support" },
  ]

  const features = [
    {
      icon: <FileText className="h-6 w-6 text-primary" />,
      title: "AI Content Generation",
      description: "Generate high-quality, SEO-optimized content for product descriptions, blog posts, and more.",
    },
    {
      icon: <BarChart3 className="h-6 w-6 text-primary" />,
      title: "Sentiment Analysis",
      description: "Analyze customer feedback and content tone to optimize your messaging and improve engagement.",
    },
    {
      icon: <Zap className="h-6 w-6 text-primary" />,
      title: "Keyword Extraction",
      description: "Automatically extract important keywords to improve SEO and content discoverability.",
    },
    {
      icon: <Code className="h-6 w-6 text-primary" />,
      title: "API Access",
      description: "Integrate our AI capabilities directly into your applications with our developer-friendly API.",
    },
    {
      icon: <Shield className="h-6 w-6 text-primary" />,
      title: "Text Summarization",
      description: "Condense long-form content into concise summaries for easier consumption and sharing.",
    },
    {
      icon: <Sparkles className="h-6 w-6 text-primary" />,
      title: "Project Management",
      description: "Organize your content into projects for better workflow management and collaboration.",
    },
  ]

  const testimonials = [
    {
      name: "Sarah Johnson",
      role: "Marketing Director",
      text: "This platform has revolutionized our content creation process. We're now able to produce high-quality content in a fraction of the time it used to take us.",
      rating: 5,
      initial: "S",
      company: "TechGrowth Inc.",
    },
    {
      name: "Michael Chen",
      role: "E-commerce Owner",
      text: "The product descriptions generated by this tool have significantly improved our conversion rates. The sentiment analysis feature is a game-changer for understanding customer feedback.",
      rating: 5,
      initial: "M",
      company: "StyleHub",
    },
    {
      name: "Alex Rodriguez",
      role: "Content Strategist",
      text: "I've tried many AI content tools, but this one stands out for its quality and versatility. The keyword extraction feature has been invaluable for our SEO efforts.",
      rating: 5,
      initial: "A",
      company: "Digital Pulse",
    },
  ]

  const plans = [
    {
      name: "Free",
      description: "Basic features for personal use",
      price: "$0",
      period: "Forever free",
      features: [
        { included: true, text: "5 content generations per month" },
        { included: true, text: "1,000 character limit" },
        { included: false, text: "Sentiment analysis" },
        { included: false, text: "Keyword extraction" },
        { included: false, text: "Text summarization" },
        { included: false, text: "API access" },
      ],
      cta: "Get Started",
      popular: false,
    },
    {
      name: "Professional",
      description: "Advanced features for professionals",
      price: "$19.99",
      period: "per month",
      features: [
        { included: true, text: "50 content generations per month" },
        { included: true, text: "5,000 character limit" },
        { included: true, text: "Sentiment analysis" },
        { included: true, text: "Keyword extraction" },
        { included: true, text: "Text summarization" },
        { included: false, text: "API access" },
      ],
      cta: "Subscribe Now",
      popular: true,
    },
    {
      name: "Enterprise",
      description: "Maximum features for businesses",
      price: "$49.99",
      period: "per month",
      features: [
        { included: true, text: "Unlimited content generations" },
        { included: true, text: "10,000 character limit" },
        { included: true, text: "Sentiment analysis" },
        { included: true, text: "Keyword extraction" },
        { included: true, text: "Text summarization" },
        { included: true, text: "API access" },
      ],
      cta: "Contact Sales",
      popular: false,
    },
  ]

  return (
    <div className="flex flex-col min-h-screen bg-black text-white">
      <header className="sticky top-0 z-40 w-full border-b border-gray-800 bg-black/95 backdrop-blur supports-[backdrop-filter]:bg-black/60">
        <div className="container flex h-14 sm:h-16 items-center space-x-2 sm:justify-between sm:space-x-0 px-4 sm:px-6">
          <div className="flex gap-4 sm:gap-6 md:gap-10">
            <Link href="/" className="flex items-center space-x-2">
              <Sparkles className="h-5 w-5 sm:h-6 sm:w-6 text-primary" />
              <span className="inline-block font-bold text-sm sm:text-base">AI Content Generator</span>
            </Link>
            <nav className="hidden md:flex gap-4 lg:gap-6">
              <Link
                href="#features"
                className="flex items-center text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
              >
                Features
              </Link>
              <Link
                href="#pricing"
                className="flex items-center text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
              >
                Pricing
              </Link>
              <Link
                href="#testimonials"
                className="flex items-center text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
              >
                Testimonials
              </Link>
              <Link
                href="/blog"
                className="flex items-center text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
              >
                Blog
              </Link>
            </nav>
          </div>
          <div className="flex flex-1 items-center justify-end space-x-2 sm:space-x-4">
            <nav className="hidden md:flex items-center space-x-2">
              <Link href="/login">
                <Button variant="ghost" size="sm" className="h-9 px-3 sm:px-4">
                  Login
                </Button>
              </Link>
              <Link href="/login">
                <Button size="sm" className="h-9 px-3 sm:px-4">Sign Up</Button>
              </Link>
            </nav>
            {/* Mobile Menu */}
            <Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}>
              <SheetTrigger asChild className="md:hidden">
                <Button variant="ghost" size="sm" className="md:hidden h-9 w-9 p-0" aria-label="Open menu">
                  <Menu className="h-5 w-5" />
                  <span className="sr-only">Open menu</span>
                </Button>
              </SheetTrigger>
              <SheetContent side="right" className="w-[300px] bg-gray-950 border-gray-800">
                <div className="flex flex-col gap-6 mt-8">
                  <div className="flex items-center justify-between">
                    <Link href="/" className="flex items-center space-x-2" onClick={() => setMobileMenuOpen(false)}>
                      <Sparkles className="h-6 w-6 text-primary" />
                      <span className="font-bold">AI Content Generator</span>
                    </Link>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setMobileMenuOpen(false)}
                      className="md:hidden"
                    >
                      <X className="h-5 w-5" />
                    </Button>
                  </div>
                  <nav className="flex flex-col gap-4">
                    <Link
                      href="#features"
                      className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      Features
                    </Link>
                    <Link
                      href="#pricing"
                      className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      Pricing
                    </Link>
                    <Link
                      href="#testimonials"
                      className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      Testimonials
                    </Link>
                    <Link
                      href="/blog"
                      className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      Blog
                    </Link>
                  </nav>
                  <div className="flex flex-col gap-3 pt-4 border-t border-gray-800">
                    <Link href="/login" onClick={() => setMobileMenuOpen(false)}>
                      <Button variant="ghost" size="sm" className="w-full justify-start">
                        Login
                      </Button>
                    </Link>
                    <Link href="/login" onClick={() => setMobileMenuOpen(false)}>
                      <Button size="sm" className="w-full bg-gradient-to-r from-primary to-indigo-600 hover:from-primary/90 hover:to-indigo-600/90 border-0">
                        Sign Up
                      </Button>
                    </Link>
                  </div>
                </div>
              </SheetContent>
            </Sheet>
          </div>
        </div>
      </header>
      <main className="flex-1">
        {mounted && (
          <motion.section
            className="relative w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-black overflow-hidden"
            initial="hidden"
            animate="visible"
            variants={fadeIn}
          >
            <motion.div
              className="absolute inset-0 z-0 opacity-30"
              style={{
                backgroundImage:
                  "radial-gradient(circle at 25% 25%, rgba(74, 222, 128, 0.2) 0%, transparent 50%), radial-gradient(circle at 75% 75%, rgba(124, 58, 237, 0.2) 0%, transparent 50%)",
              }}
            />
            <motion.div style={{ opacity, y }} className="absolute top-[-10%] right-[-10%] z-0">
              <div className="w-[500px] h-[500px] rounded-full bg-gradient-to-br from-primary/20 to-indigo-500/20 blur-3xl" />
            </motion.div>
            <div className="container relative z-10 px-4 sm:px-6">
              <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
                <motion.div
                  className="flex flex-col justify-center space-y-4"
                  initial="hidden"
                  animate="visible"
                  variants={fadeIn}
                  transition={{ duration: 0.5 }}
                >
                  <div className="space-y-3 sm:space-y-4">
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.2, duration: 0.5 }}
                    >
                      <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl font-bold tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-primary to-indigo-500 leading-tight">
                        AI-Powered Content Generation for Modern Businesses
                      </h1>
                    </motion.div>
                    <motion.p
                      className="max-w-[600px] text-muted-foreground text-base sm:text-lg md:text-xl"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.4, duration: 0.5 }}
                    >
                      Create high-quality, SEO-optimized content in seconds. Boost your marketing efforts with advanced
                      AI tools for content creation, sentiment analysis, and more.
                    </motion.p>
                  </div>
                  <motion.div
                    className="flex flex-col gap-3 sm:gap-2 min-[400px]:flex-row pt-2"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6, duration: 0.5 }}
                  >
                    <Link href="/login" className="w-full min-[400px]:w-auto">
                      <Button
                        size="lg"
                        className="w-full min-[400px]:w-auto gap-1 bg-gradient-to-r from-primary to-indigo-600 hover:from-primary/90 hover:to-indigo-600/90 border-0 h-11 sm:h-12 text-base"
                      >
                        Get Started
                        <ArrowRight className="h-4 w-4" />
                      </Button>
                    </Link>
                    <Link href="#features" className="w-full min-[400px]:w-auto">
                      <Button size="lg" variant="outline" className="w-full min-[400px]:w-auto border-gray-800 h-11 sm:h-12 text-base">
                        Learn More
                      </Button>
                    </Link>
                  </motion.div>
                  <motion.div
                    className="pt-6 sm:pt-8 grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4"
                    variants={staggerContainer}
                    initial="hidden"
                    animate="visible"
                  >
                    {stats.map((stat, i) => (
                      <motion.div
                        key={i}
                        className="flex flex-col items-center p-3 sm:p-4 rounded-lg bg-gray-900/50 border border-gray-800"
                        variants={fadeIn}
                      >
                        <span className="text-xl sm:text-2xl md:text-3xl font-bold text-primary">{stat.value}</span>
                        <span className="text-xs sm:text-sm text-muted-foreground text-center">{stat.label}</span>
                      </motion.div>
                    ))}
                  </motion.div>
                </motion.div>
                <motion.div
                  className="mx-auto flex items-center justify-center"
                  initial="hidden"
                  animate="visible"
                  variants={scaleUp}
                >
                  <div className="relative w-full h-[250px] sm:h-[300px] md:h-[350px] lg:h-[420px] overflow-hidden rounded-lg border border-gray-800 bg-gradient-to-br from-gray-950 to-gray-900 p-3 sm:p-4">
                    <div className="absolute top-4 left-4 right-4 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <div className="h-3 w-3 rounded-full bg-red-500" />
                        <div className="h-3 w-3 rounded-full bg-yellow-500" />
                        <div className="h-3 w-3 rounded-full bg-green-500" />
                      </div>
                      <div className="text-xs text-gray-400">AI Content Generator</div>
                    </div>
                    <motion.div
                      className="mt-8 space-y-4 p-2"
                      initial="hidden"
                      animate="visible"
                      variants={staggerContainer}
                    >
                      {[...Array(9)].map((_, i) => (
                        <motion.div
                          key={i}
                          className={`h-4 ${
                            i % 2 === 0 ? "w-full" : i % 3 === 0 ? "w-3/4" : "w-5/6"
                          } rounded bg-gray-800 ${i < 3 ? "animate-pulse" : ""}`}
                          variants={fadeIn}
                          transition={{ duration: 0.3 }}
                        />
                      ))}
                    </motion.div>
                  </div>
                </motion.div>
              </div>
            </div>
            <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-black to-transparent" />
          </motion.section>
        )}

        <section className="relative py-12 sm:py-16 md:py-24 bg-gradient-to-b from-black to-gray-950">
          <div className="container px-4 sm:px-6">
            <motion.div
              className="max-w-3xl mx-auto text-center mb-8 sm:mb-12"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 sm:mb-4">How It Works</h2>
              <p className="text-muted-foreground text-sm sm:text-base">
                Our AI-powered platform simplifies content creation with an intuitive three-step process
              </p>
            </motion.div>

            <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-6 sm:gap-8">
              {[
                {
                  step: "1",
                  title: "Input Your Requirements",
                  description: "Specify your content type, topic, and preferences to guide the AI generation process.",
                  icon: <FileText className="h-8 w-8 text-primary" />,
                },
                {
                  step: "2",
                  title: "AI Generates Content",
                  description:
                    "Our advanced AI models create high-quality, original content tailored to your specifications.",
                  icon: <Sparkles className="h-8 w-8 text-primary" />,
                },
                {
                  step: "3",
                  title: "Analyze & Optimize",
                  description:
                    "Review, edit, and enhance your content with our built-in SEO and sentiment analysis tools.",
                  icon: <BarChart3 className="h-8 w-8 text-primary" />,
                },
              ].map((item, i) => (
                <motion.div
                  key={i}
                  className="flex flex-col items-center text-center p-4 sm:p-6 rounded-lg bg-gray-900/50 border border-gray-800"
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1, duration: 0.5 }}
                >
                  <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-primary/20 flex items-center justify-center mb-3 sm:mb-4">
                    {item.icon}
                  </div>
                  <div className="bg-primary/20 text-primary font-bold rounded-full w-7 h-7 sm:w-8 sm:h-8 flex items-center justify-center mb-3 sm:mb-4 text-sm sm:text-base">
                    {item.step}
                  </div>
                  <h3 className="text-lg sm:text-xl font-bold mb-2">{item.title}</h3>
                  <p className="text-muted-foreground text-sm sm:text-base">{item.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        <section id="features" className="w-full py-12 sm:py-16 md:py-24 lg:py-32 bg-gray-950">
          <div className="container px-4 sm:px-6">
            <motion.div
              className="flex flex-col items-center justify-center space-y-3 sm:space-y-4 text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-900 px-3 py-1 text-xs sm:text-sm">Features</div>
                <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">
                  Everything You Need for Content Creation
                </h2>
                <p className="max-w-[900px] text-muted-foreground text-sm sm:text-base md:text-lg lg:text-xl px-4">
                  Our platform combines the power of AI with intuitive tools to help you create, analyze, and optimize
                  content for your business.
                </p>
              </div>
            </motion.div>
            <motion.div
              className="mx-auto grid max-w-5xl grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6 lg:grid-cols-3 mt-8 sm:mt-12"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={staggerContainer}
            >
              {features.map((feature, index) => (
                <motion.div
                  key={index}
                  className="flex flex-col items-center space-y-2 sm:space-y-3 rounded-lg border border-gray-800 p-4 sm:p-6 bg-black/50 hover:bg-black/80 transition-colors"
                  variants={featureVariants}
                  whileHover={{ y: -5 }}
                  transition={{ type: "spring", stiffness: 300, damping: 10 }}
                >
                  <div className="flex h-10 w-10 sm:h-12 sm:w-12 items-center justify-center rounded-full border border-gray-800 bg-gray-950">
                    {feature.icon}
                  </div>
                  <h3 className="text-lg sm:text-xl font-bold text-center">{feature.title}</h3>
                  <p className="text-xs sm:text-sm text-muted-foreground text-center">{feature.description}</p>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        <section className="w-full py-12 sm:py-16 md:py-24 bg-black relative overflow-hidden">
          <div className="absolute inset-0 z-0 opacity-30">
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-primary/5 to-indigo-500/5" />
          </div>
          <div className="container relative z-10 px-4 sm:px-6">
            <motion.div
              className="max-w-3xl mx-auto text-center mb-8 sm:mb-12"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              <div className="inline-block rounded-lg bg-gray-900 px-3 py-1 text-xs sm:text-sm mb-3 sm:mb-4">Use Cases</div>
              <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 sm:mb-4">Perfect for Various Industries</h2>
              <p className="text-muted-foreground text-sm sm:text-base px-4">
                Our AI content generation platform serves diverse business needs across multiple sectors
              </p>
            </motion.div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
              {[
                {
                  icon: <Laptop className="h-8 w-8 text-primary" />,
                  title: "E-commerce",
                  description: "Create compelling product descriptions that convert browsers into buyers.",
                },
                {
                  icon: <Globe className="h-8 w-8 text-primary" />,
                  title: "Digital Marketing",
                  description: "Generate SEO-optimized blog posts and marketing copy that drives traffic.",
                },
                {
                  icon: <Users className="h-8 w-8 text-primary" />,
                  title: "Customer Support",
                  description: "Craft consistent responses for FAQs and support documentation.",
                },
                {
                  icon: <FileText className="h-8 w-8 text-primary" />,
                  title: "Content Creation",
                  description: "Produce engaging articles, social media posts, and email newsletters.",
                },
              ].map((item, i) => (
                <motion.div
                  key={i}
                  className="flex flex-col p-4 sm:p-6 rounded-lg bg-gray-900/50 border border-gray-800"
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1, duration: 0.5 }}
                >
                  <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full bg-primary/20 flex items-center justify-center mb-3 sm:mb-4">
                    {item.icon}
                  </div>
                  <h3 className="text-lg sm:text-xl font-bold mb-2">{item.title}</h3>
                  <p className="text-muted-foreground text-sm sm:text-base">{item.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        <section id="pricing" className="w-full py-12 sm:py-16 md:py-24 lg:py-32 bg-black">
          <div className="container px-4 sm:px-6">
            <motion.div
              className="flex flex-col items-center justify-center space-y-3 sm:space-y-4 text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-900 px-3 py-1 text-xs sm:text-sm">Pricing</div>
                <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">Choose Your Plan</h2>
                <p className="max-w-[900px] text-muted-foreground text-sm sm:text-base md:text-lg lg:text-xl px-4">
                  Flexible pricing options to meet the needs of businesses of all sizes.
                </p>
              </div>
            </motion.div>
            <motion.div
              className="mx-auto grid max-w-5xl grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 mt-8 sm:mt-12"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={staggerContainer}
            >
              {plans.map((plan, index) => (
                <motion.div
                  key={index}
                  className={`flex flex-col rounded-lg border ${
                    plan.popular ? "border-primary" : "border-gray-800"
                  } bg-gray-950 p-4 sm:p-6 relative`}
                  variants={featureVariants}
                  whileHover={{ y: -5 }}
                  transition={{ type: "spring", stiffness: 300, damping: 10 }}
                >
                  {plan.popular && (
                    <div className="absolute -top-2.5 sm:-top-3 left-1/2 transform -translate-x-1/2 bg-primary text-black text-xs font-bold px-2.5 sm:px-3 py-0.5 sm:py-1 rounded-full">
                      POPULAR
                    </div>
                  )}
                  <div className="space-y-2">
                    <h3 className="text-xl sm:text-2xl font-bold">{plan.name}</h3>
                    <p className="text-xs sm:text-sm text-muted-foreground">{plan.description}</p>
                  </div>
                  <div className="mt-4 text-3xl sm:text-4xl font-bold">{plan.price}</div>
                  <p className="text-xs sm:text-sm text-muted-foreground mt-1">{plan.period}</p>
                  <ul className="mt-4 sm:mt-6 space-y-2 text-xs sm:text-sm">
                    {plan.features.map((feature, featureIndex) => (
                      <li key={featureIndex} className="flex items-center">
                        {feature.included ? (
                          <CheckCircle2 className="mr-2 h-4 w-4 text-green-500" />
                        ) : (
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            className="mr-2 h-4 w-4 opacity-50"
                          >
                            <path d="M18 6 6 18"></path>
                            <path d="m6 6 12 12"></path>
                          </svg>
                        )}
                        <span className={!feature.included ? "opacity-50" : ""}>{feature.text}</span>
                      </li>
                    ))}
                  </ul>
                  <div className="mt-4 sm:mt-6">
                    <Link href="/login" className="block">
                      <Button
                        className={`w-full h-10 sm:h-11 ${
                          plan.popular
                            ? "bg-gradient-to-r from-primary to-indigo-600 hover:from-primary/90 hover:to-indigo-600/90 border-0"
                            : ""
                        }`}
                      >
                        {plan.cta}
                      </Button>
                    </Link>
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        <section id="testimonials" className="w-full py-12 sm:py-16 md:py-24 lg:py-32 bg-gray-950">
          <div className="container px-4 sm:px-6">
            <motion.div
              className="flex flex-col items-center justify-center space-y-3 sm:space-y-4 text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-900 px-3 py-1 text-xs sm:text-sm">Testimonials</div>
                <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">What Our Customers Say</h2>
                <p className="max-w-[900px] text-muted-foreground text-sm sm:text-base md:text-lg lg:text-xl px-4">
                  Don't just take our word for it. See what our customers have to say about our platform.
                </p>
              </div>
            </motion.div>
            <motion.div
              className="mx-auto grid max-w-5xl grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 mt-8 sm:mt-12"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={staggerContainer}
            >
              {testimonials.map((testimonial, index) => (
                <motion.div
                  key={index}
                  className="flex flex-col rounded-lg border border-gray-800 bg-black/50 p-4 sm:p-6 hover:bg-black/80 transition-colors"
                  variants={featureVariants}
                  whileHover={{ y: -5 }}
                  transition={{ type: "spring", stiffness: 300, damping: 10 }}
                >
                  <div className="flex items-center space-x-2 mb-3 sm:mb-4">
                    <div className="h-9 w-9 sm:h-10 sm:w-10 rounded-full bg-gray-800 flex items-center justify-center text-base sm:text-lg font-bold flex-shrink-0">
                      {testimonial.initial}
                    </div>
                    <div className="min-w-0">
                      <h3 className="font-bold text-sm sm:text-base truncate">{testimonial.name}</h3>
                      <p className="text-xs sm:text-sm text-muted-foreground truncate">{testimonial.role}</p>
                    </div>
                  </div>
                  <div className="mt-2 sm:mt-4">
                    <p className="text-xs sm:text-sm text-muted-foreground line-clamp-4">{testimonial.text}</p>
                  </div>
                  <div className="mt-2 text-xs text-muted-foreground truncate">{testimonial.company}</div>
                  <div className="mt-3 sm:mt-4 flex">
                    {[...Array(testimonial.rating)].map((_, starIndex) => (
                      <Star key={starIndex} className="h-3 w-3 sm:h-4 sm:w-4 text-yellow-500 fill-yellow-500" />
                    ))}
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        <motion.section
          className="w-full py-12 sm:py-16 md:py-24 lg:py-32 bg-black"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <div className="container px-4 sm:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 sm:space-y-6 text-center">
              <div className="space-y-2 sm:space-y-3">
                <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">Ready to Get Started?</h2>
                <p className="max-w-[900px] text-muted-foreground text-sm sm:text-base md:text-lg lg:text-xl px-4">
                  Join thousands of businesses already using our AI-powered content generation platform.
                </p>
              </div>
              <motion.div
                className="flex flex-col gap-3 sm:gap-2 w-full sm:w-auto min-[400px]:flex-row"
                whileHover={{ scale: 1.05 }}
                transition={{ type: "spring", stiffness: 400, damping: 10 }}
              >
                <Link href="/login" className="w-full min-[400px]:w-auto">
                  <Button
                    size="lg"
                    className="w-full min-[400px]:w-auto gap-1 bg-gradient-to-r from-primary to-indigo-600 hover:from-primary/90 hover:to-indigo-600/90 border-0 h-11 sm:h-12 text-base"
                  >
                    Sign Up Now
                    <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
                <Link href="/login" className="w-full min-[400px]:w-auto">
                  <Button size="lg" variant="outline" className="w-full min-[400px]:w-auto border-gray-800 h-11 sm:h-12 text-base">
                    Login
                  </Button>
                </Link>
              </motion.div>
            </div>
          </div>
        </motion.section>
      </main>
      <footer className="w-full py-6 sm:py-8 bg-gray-950 border-t border-gray-800">
        <div className="container px-4 sm:px-6">
          <div className="grid gap-6 sm:gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-5">
            <div className="space-y-4">
              <Link href="/" className="flex items-center space-x-2">
                <Sparkles className="h-6 w-6 text-primary" />
                <span className="font-bold">AI Content Generator</span>
              </Link>
              <p className="text-sm text-muted-foreground">
                AI-powered content generation for modern businesses. Create high-quality, SEO-optimized content in
                seconds.
              </p>
            </div>
            <div className="space-y-4">
              <h3 className="font-medium">Product</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link href="#features" className="text-muted-foreground hover:text-foreground">
                    Features
                  </Link>
                </li>
                <li>
                  <Link href="#pricing" className="text-muted-foreground hover:text-foreground">
                    Pricing
                  </Link>
                </li>
                <li>
                  <Link href="#testimonials" className="text-muted-foreground hover:text-foreground">
                    Testimonials
                  </Link>
                </li>
              </ul>
            </div>
            <div className="space-y-4">
              <h3 className="font-medium">Company</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link href="/about" className="text-muted-foreground hover:text-foreground">
                    About
                  </Link>
                </li>
                <li>
                  <Link href="/blog" className="text-muted-foreground hover:text-foreground">
                    Blog
                  </Link>
                </li>
                <li>
                  <Link href="/careers" className="text-muted-foreground hover:text-foreground">
                    Careers
                  </Link>
                </li>
              </ul>
            </div>
            <div className="space-y-4">
              <h3 className="font-medium">Newsletter</h3>
              <p className="text-sm text-muted-foreground mb-2">
                Get the latest updates and exclusive content delivered to your inbox.
              </p>
              <NewsletterForm />
            </div>
            <div className="space-y-4">
              <h3 className="font-medium">Legal</h3>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link href="/privacy" className="text-muted-foreground hover:text-foreground">
                    Privacy Policy
                  </Link>
                </li>
                <li>
                  <Link href="/terms" className="text-muted-foreground hover:text-foreground">
                    Terms of Service
                  </Link>
                </li>
                <li>
                  <Link href="/cookies" className="text-muted-foreground hover:text-foreground">
                    Cookie Policy
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="mt-8 border-t border-gray-800 pt-6 text-center text-sm text-muted-foreground">
            © {new Date().getFullYear()} AI Content Generator. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  )
}
